### ISSUE TITLE
Aprender los conceptos básicos de Docker

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#20]
- Docker Documentation - https://docs.docker.com/
- [freeCodeCamp.org]. (2019, Aug 16). _Docker Tutorial for Beginners - A Full DevOps Course on How to Run Applications in Containers_ [Video File]. Retrieved from https://www.youtube.com/watch?v=fqMOX6JJhGo

**Comment by gcm1001** [comment]
Tras haber repasado todos los conceptos básicos de Docker, a continuación mostraré los primeros pasos que llevaré a cabo para la integración progresiva de Docker en mi entorno de desarrollo. 

El primer paso para incorporar _Docker_ en mi entorno de desarrollo (Arch Linux) será instalar los paquetes `docker` y `docker-compose`.

```
pacman -S docker docker-compose
```

Una vez instalado, procederé a desarrollar, por partes, el fichero `Dockerfile`. Este me permitirá preparar el entorno de desarrollo a partir de una simple lista de comandos. 

El primer paso es **crear el fichero** `Dockerfile` (sin extensión alguna).


```
nano Dockerfile 
```

Una vez creado, procedo a su configuración. 
La primera instrucción de la lista será `FROM`. Esta nos permite **configurar el sistema operativo** de la imagen que vamos a crear. Para escoger el argumento he llevado a cabo dos pasos:
1. Apuntar los requisitos de mi aplicación web (Omeka)
    - Sistema Operativo: Linux
    - Apache HTTP server
    - MySQL versión 5.0 o mayor
2. Buscar en el repositorio [DockerHub](https://hub.docker.com/) una imagen que cumpla con todo o parte de lo anterior.
La imagen que he escogido ha sido la [oficial de php](https://hub.docker.com/_/php), en concreto `php:7.4-apache` (SO Debian con Apache httpd junto con PHP).

```
FROM php:7.4-apache
```

En siguiente paso será **instalar todos los paquetes** necesarios para que el entorno de desarrollo sea válido, que son:
- `build-essentials` : nos permitirá instalar paquetes en nuestro SO Debian.
- `ca-certificates` :  permite que las aplicaciones basadas en SSL comprueben la autenticidad de las conexiones SSL.
- `git` : necesario para clonar el repositorio oficial de Omeka.
- `unzip` : dado que el repositorio de Omeka viene comprimido con formato .zip, esta herramienta nos permite descomprimir la aplicación web.
- `imagemagick` : uno de los requisitos de Omeka es tener instalado imagemagick. Este lo utiliza para la generación de los diferentes tipos de miniaturas que podemos ver tanto en la administración del sistema, como en la parte pública.
- `zlib1g` y `zlib1g-dev` : comprimir archivos.
- `docker-php-ext-install exif curl mbstring mysqli pdo pdo_mysql zip` : extensiones PHP necesarias para el correcto funcionamiento de Omeka.

```
FROM php:7.4-apache

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
        build-essential \
        ca-certificates \
        git \
        unzip \
        imagemagick \
        zlib1g \
        zlib1g-dev && \
        docker-php-ext-install exif mbstring mysqli pdo pdo_mysql zip
```

Ya tenemos instalados todos los paquetes necesarios en nuestra imagen Docker para poner en marcha el servidor web. 

Lo siguiente sería desplegar la aplicación web (Omeka) sobre Apache. Este paso lo dejaré para más adelante ya que me interesa mejorar mi formación en Docker con el fin de realizar una configuración óptima del fichero `Dockerfile`.

**Comment by gcm1001** [comment]
Continuando con la implementación del fichero `Dockerfile`, ahora toca desplegar el gestor de contenido Omeka sobre el servidor HTTP Apache. 

En primer lugar hay que realizar la **configuración del servidor** a través del fichero `/etc/apache2.conf`. Para ello, gracias a la instrucción `RUN` que nos permite ejecutar comandos dentro de nuestra imagen, estableceré el nombre del servidor.

```
RUN echo "ServerName localhost" >> /etc/apache2.conf
```
El siguiente paso es **alojar los ficheros de la aplicación web sobre el directorio web** `/var/www/html` establecido por defecto. La instrucción `WORKDIR` nos permitirá desplazarnos al directorio especificado y con la instrucción `ADD` podremos añadir, bien desde nuestro ordenador o bien desde una url, los ficheros correspondientes a la aplicación web.
Crearé además una variable de entorno a través de la instrucción `ENV` para indicar qué versión de Omeka voy a instalar.
```
ENV OMEKA_VERSION 2.7.1
WORKDIR /var/www/html
ADD https://github.com/omeka/Omeka/releases/download/v${OMEKA_VERSION}/omeka-${OMEKA_VERSION}.zip omeka-${OMEKA_VERSION}.zip
```

Ahora, dado que los ficheros están comprimidos, realizamos las operaciones necesarias para **descomprimir** y posteriormente eliminar el fichero comprimido.
```
RUN unzip -q omeka-${OMEKA_VERSION}.zip && mv omeka-${OMEKA_VERSION}/* /var/www/html/.
RUN rm -r omeka-${OMEKA_VERSION}.zip
```

En este momento, ya tendríamos todos los ficheros por defecto de Omeka alojados en el servidor. La siguiente tarea será **modificar aquellos ficheros que requieran ser configurados**. 
La forma más sencilla de realizar esta tarea es sustituir estos archivos por los nuestros ya configurados. Esta operación se puede llevar a cabo a través de la instrucción `ADD`. 
```
ADD /omeka/.htaccess /var/www/html/.htaccess
ADD /omeka/application/config.ini /var/www/html/application/config/config.ini
```
Actualizo **permisos** para que Apache tenga acceso a todos los ficheros de la aplicación web.
```
RUN chmod -R 777 files
RUN chown -R www-data:www-data files
RUN chown www-data:www-data application/config/config.ini
```
**Elimino** todos aquellos **temas y plugins** que no daré uso y vienen instalados **por defecto**. También eliminaré el fichero de configuración de la base de datos `db.ini`  ya que está sin configurar.
```
RUN rm -rf /var/www/html/themes/* && rm /var/www/html/db.ini
RUN rm -rf /var/www/html/plugins/ExhibitBuilder && rm -rf /var/www/html/plugins/Coins   
```  
Por último, **añado el tema** que estoy desarrollando **y todos los plugins** escogidos y desarrollados hasta ahora.
```  
ADD /omeka/themes /var/www/html/themes
ADD /omeka/plugins /var/www/html/plugins
```  
Para concluir, realizo las **operaciones de limpieza** correspondientes, activo el **`mod_rewrite`** de Apache y **reinicio el servidor**.

```
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN a2enmod rewrite && service apache2 restart
```


De momento, ya tendría configurado el fichero `Dockerfile`. Ahora solo falta montar la imagen a través del siguiente comando:
```
docker build -t omeka_cenieh:latest .  
```
La nueva imagen generada, con nombre `omeka_cenieh`, ya podrá ser montada sobre un contenedor Docker.

**Comment by clopezno** [comment]
Buen trabajo. La tarea está perfectamente documentada .
