### ISSUE TITLE
Sincronizar mapa con el elemento 'Spatial Coverage'

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#23]
A raíz de la funcionalidad implementada en la tarea #22,  es necesario almacenar este nuevo formato de localización sobre el elemento '_Spatial Coverage_' del esquema de metadatos '_Dublin Core_'.

Este nuevo formato almacena una coordenada por cada vértice del rectángulo, es decir, cuatro puntos:

![Untitled Diagram](https://user-images.githubusercontent.com/44768603/76944057-a9541d80-6900-11ea-9da1-33a6b064b2b1.png)

Teniendo en cuenta que el esquema de metadatos objeto (_AO-CAT_) emplea el elemento _AO_Spatial_Region_BBox_ para representar zonas geográficas rectangulares, y que este a su vez está compuesto por los elementos:

- _has_bounding_box_min_lat_ 
- _has_bounding_box_min_lon_
- _has_bounding_box_max_lat_
- _has_bounding_box_max_lon_

Tendré por lo tanto que sincronizar únicamente las dos coordenadas correspondientes a los puntos mínimo y máximo del rectángulo, es decir, los puntos A (mínimo) y C (máximo) del ejemplo.

**Comment by clopezno** [comment]
Generalmente para representar un rectángulo en 2D solo se guarda un punto (esquina superior izquierda),  su anchura (resto de longitudes) y su altura (resto de latitudes). 
No sé si en geolocalización se utiliza este esquema de almacenamiento. Desde luego parece más s eficiente.
