### ISSUE TITLE
Implementar un sistema de estados para las colecciones

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#29]
Se pretende elaborar un plugin que permita asociar a cada colección uno de los siguientes estados:
- Privada: no está lista para ser publicada. 
- Disponible: cumple con los requisitos para ser publicada.
- Compartida: ya ha sido publicada. 

La idea es que cada colección sea inicializada con el estado 'Privada'. En el momeno que el operador considere oportuno, deberá indicar (a través de un botón) que la colección ya está lista para ser publicada. 
Al efectuar este paso, el sistema escaneará todos los datos de la colección para ver si cumplen con todos los requisitos establecidos, en cuyo caso actualizará el estado a 'Disponible'.
Todas aquellas colecciones con estado 'Disponible' podrán ser publicadas en A+. El sistema deberá actualizar el estado a 'Publicada' cuando dicha colección esté dentro del catálogo A+.
Si un operario modifica una colección con estado 'Publicada' o 'Disponible', vuelve al estado 'Privada'.

P.D: La nomenclatura de los estados puede variar.
P.D2: El paso entre estados descrito puede verse alterado ya que está aún en proceso de desarrollo.

**Comment by gcm1001** [comment]
## Plugins adicionales
En primer lugar, explicaré el por qué he instalado dos nuevos plugins en la infraestructura. 
> **Nombre del plugin**: HistoryLog
> **Descripción**: permite llevar un registro de las acciones que se cometen en la plataforma, es decir, si un administrador u operario añade/modifica/elimina algún dato, esta operación se verá reflejada en una tabla de registros. 
> **Utilidad**: a la hora de realizar el sistema de estados, este plugin me permitirá identificar qué persona/usuario modificó el estado, pudiendo así realizar un seguimiento adecuado del avance de la colección.
> **Screenshot**:
![Screenshot_20200413_110427](https://user-images.githubusercontent.com/44768603/79108463-aff67900-7d76-11ea-8a4e-7c90f6f4b472.png)

> **Nombre del plugin**: SimpleVocab
> **Descripción**: permite modificar el tipo de entrada (lista de selección) para un elemento del esquema de metadatos. 
> **Utilidad**: dado que nuestro sistema de estados va a estar compuesto por un conjunto de estados prefijados, no nos interesa que el usuario introduzca, en modo texto, el nombre del estado. Haciendo uso de este plugin el usuario podrá escoger el estado a través de una lista
> **Screenshot**:
![Screenshot_20200413_111242](https://user-images.githubusercontent.com/44768603/79108984-bc2f0600-7d77-11ea-9fe4-84e68ee70f77.png)



## Actualizaciones

### Estados
Actualmente el sistema de estados consta de **6 estados**, de los cuales 5 han sido ya implementados (en negrita ) :

1. **Incomplete**: 
    - Requisitos: ninguno.
    - Acción: ninguna.
    - Descripción: el esquema de metadatos está incompleto y/o alguno de sus campos no están suficientemente desarrollados.
2. **Complete**: 
    - Requisitos: todos los elementos requeridos por el esquema de metadatos objetivo (AO-CAT) deben estar rellenados.
        - Elementos: _'Identifier','Title','Subject','Language','Date','Rights','Publisher','Contributor','Creator', 'Spatial Coverage'_.
    - Acción: se comprueba que cada ítem almacenado en la colección tiene rellenado cada uno de los campos. 
    - Descripción: el esquema de metadatos del ítem está completo, es decir, contiene todos los elementos obligatorios.
3. **Mapped**
    - Requisitos: la colección asociada a cada ítem debe de tener especificado el identificador asociado al mapeo.
    - Acción: se comprueba en cada colección que el campo responsable de almacenar al identificador del mapeo no está vacío.
    - Descripción: el conjunto de metadatos del ítem puede ser mapeado (traducido) al esquema de metadatos de AriadnePlus (AO-CAT).
4.  _[OPCIONAL]_ **Enriched**
    - Requisitos: la colección asociada a cada ítem debe de tener especificado la colección de Period0 que ha utilizado para establecer los datos temporales o bien el archivo JSON para mapear el vocabulario utilizado al vocabulario Getty ATT.
    - Acción: se comprueba, en cada colección, que el campo responsable de almacenar la url de Period0 o el archivo de mapeo JSON no está vacío.
    - Descripción: el conjunto de metadatos del ítem ha sido enriquecido.
5. **Ready to Publish**
    - Requisitos: como es lógico, cada uno de los ítems han tenido que pasar satisfactoriamente todas las fases previas (a excepción de la fase _Enriched_).
    - Acción: se envía, de forma automática, un mensaje electrónico al responsable de introducir datos en AriadnePLus. El contenido de este es el siguiente:
        - Nombre de la colección.
        - Url para descargar, en formato .XML, toda la colección.
        - Url para la acceder a la colección a través del protocolo OAI-PMH.
        - Url de la colección Period0 asociada.
        -  _[En desarrollo]_ Url para descargar el archivo .JSON asociado al mapeo del vocabulario.
    - Descripción: el ítem está listo para ser publicado.
6. _[En desarrollo]_ Published
    - Requisitos: los ítems deben estar publicados en el catálogo AriadnePlus.
    - Acción: a través de una petición a la base de datos de AriadnePlus, se realiza una búsqueda del identificador original de cada ítem. Si da resultado significa que el ítem ha sido publicado.
    - Descripción: el ítem ha sido publicado en Ariadne+.

### Panel de administración
Desde el panel de administración se pueden actualizar los estados, pudiendo trabajar únicamente sobre una colección determinada. A través del botón `Stage` se realiza la petición de cambio, activando la acción asociada al estado siguiente.
Siempre que la acción devuelva un resultado satisfactorio, se realiza el cambio de estado.

![Screenshot_20200413_114056](https://user-images.githubusercontent.com/44768603/79111014-fbf7ec80-7d7b-11ea-9ec5-e9663ed5f420.png)

**Comment by clopezno** [comment]
Añadir un diagrama de transicción de estados UML  puede ayudar a entender mejor *los  estados deel proceso de publicación de información  del CENIEH en ARIADNE*.

En las transicciones de estado hay que indicar las operación  del menú que permite  el cambio de estado. Además  me parece interesenta añadir un estado de inicio, para representar la información que va a hacer seguimiento para su publicación en ARIADNE (similar al add de git). 
Creo que es necesario  un estado final para poder diseñar casos en los que la información ha sido publicada en ARIADNE pero haya sufrido una modificación dentro del CENIEH y no esté actualizada en ARIADNE (similar a push git).

**Comment by gcm1001** [comment]
> Añadir un diagrama de transicción de estados UML puede ayudar a entender mejor _los estados deel proceso de publicación de información del CENIEH en ARIADNE_.

Me parece buena idea, ahora creo la Issue correspondiente.

> En las transicciones de estado hay que indicar las operación del menú que permite el cambio de estado. Además me parece interesenta añadir un estado de inicio, para representar la información que va a hacer seguimiento para su publicación en ARIADNE (similar al add de git).
> Creo que es necesario un estado final para poder diseñar casos en los que la información ha sido publicada en ARIADNE pero haya sufrido una modificación dentro del CENIEH y no esté actualizada en ARIADNE (similar a push git).

Si no he entendido mal, las funciones a implementar serían:

1. Cuando se ejecute un cambio de estado, mostrar en pantalla un mensaje informativo de la acción que se está llevando a cabo de forma interna.
    - Actualmente genero _logs_ en cada ejecución (a nivel informativo). Aquí dejo unos ejemplos:

_Incomplete > Complete Fallido_
```
2020-04-13T09:34:06+02:00 INFO (6): [AriadnePlusMonitor][Stage] Record #0 is not valid. Spatial Coverage is empty.
2020-04-13T09:34:06+02:00 INFO (6): [AriadnePlusMonitor][Stage] 0 records staged to "Complete" for element "" (#0).
```
_Incomplete > Complete Completado_
```
2020-04-13T09:34:32+02:00 INFO (6): [AriadnePlusMonitor][Stage] Element #0 ("") of record #369 staged to "Complete" (1/1).
2020-04-13T09:34:32+02:00 INFO (6): [AriadnePlusMonitor][Stage] 1 records staged to "Complete" for element "" (#0).
```   
2. Crear un estado inicial ( previo a 'Incomplete' ) que identifique aquellos ítems que van a ser sometidos al proceso de importación.
3. Crear un estado final ( posterior a 'Published' ) que identifique aquellos ítems publicados cuyos metadatos existentes en Ariadne+ no coinciden con los metadatos existentes en el gestor, es decir, que han sido modificados internamente.
    - Habría que añadir un nuevo `Stage` en `Published` que ejecutara la acción responsable de comprobar las modificaciones existentes.

**Comment by clopezno** [comment]
La **utilización del Log me parece una muy buena idea**.

Desde el punto de vista de diseño puedes considerar una estructura compuesto (_Elemento Publicable, Colección, Item... e incluir las colecciones y elementos concretos del CENIEH_). Además necesitas definir unas operaciones `crear(), editar(), actualizar(),publicarAriadne(), despublicarenAriadne()`... Asociado al Elemento Publicable  (abstracto) podrás asociar el estado.

Repasa los patrones de diseño [Compuesto](https://sourcemaking.com/design_patterns/composite) y [Estado](https://sourcemaking.com/design_patterns/state) por si te sirven para implementar la solución. La ventaja fundamental de este diseño es que lo dejas preparado para futuras extensiones de colecciones del CENIEH.

**Comment by gcm1001** [comment]
En esta última actualización, he añadido al diseño un sistema de identificación para determinar en qué estado del proceso de publicación CENIEH->Ariadne se encuentran las colecciones.

![Screenshot_20200416_130530](https://user-images.githubusercontent.com/44768603/79449142-fc45f100-7fe2-11ea-81f3-8ac80fd1aaf1.png)

Además, como podemos observar en las placas identificativas, he añadido un nuevo estado inicial, **`Proposed`**, cuya función es identificar a aquellas colecciones recién consideradas para su publicación en Ariadne+.
Desde este nuevo estado se puede puede llevar a cabo una nueva acción, **`Assign State`**, la cual ejecuta una serie de chequeos para determinar qué estado es el adecuado para asignar a la colección.
> **`Proposed`**
Al introducir una colección al gestor, la seleccionamos a través del botón/placa "No Status - Add to pubish process" y automáticamente esta colección adquiere el estado inicial "Proposed". **Desde este momento la colección será visible desde el monitor de Ariadne+**.
>
>  ![Screenshot_20200416_132245](https://user-images.githubusercontent.com/44768603/79450669-7aa39280-7fe5-11ea-9ad9-695986cde3af.png)
>
> **Funcionamiento de `Assign State`**
>A continuación, desde el monitor, seleccionando esta misma colección vemos lógicamente que sus ítems se encuentran en estado `Proposed`. Si clicamos sobre el botón `Assign State` se ejecutan, de forma interna, los siguientes chequeos/acciones **de forma secuencial**:
> 1. ¿ Todos los metadatos de la colección tienen los elementos mínimos requeridos ? 
>     - **SI**: Complete
>     - **NO**: Incomplete
>  2. ¿ La colección tiene asociado un mapeo en D4Science (X3ML Mapping Tool) ?
>     - **SI**: Mapped
>     - **NO**: Complete
>  3. ¿ La colección usa una colección de period0 o tiene asociado algún fichero JSON (Getty ATT) ? 
>     - **SI**: Enriched 
>     - **NO**: Mapped
> 4. ¿ Se ha enviado con éxito un mensaje a Ariadne+ indicando la url de la colección (.xml & OAI-PMH), identificador del mapeo (X3ML Mapping Tool), url de Period0 y url del archivo JSON ?
>     - **SI**: Ready to publish
>     - **NO**: Enriched
> 5. ¿ Existe la colección en Ariadne+ (SPARQL) ? 
>     - **SI**: Published
>     - **NO**: Ready to publish.
>
> **CONDICIÓN DE PARADA**: La ejecución secuencial se para en el momento que se obtiene como respuesta un NO, asignando el estado asociado a ese NO a la colección seleccionada. La única parada posible por parte del SI es en el caso de que la colección propuesta ya estuviera publicada en Ariadne+ (Estado "Published").
