### ISSUE TITLE
[AriadnePlus Monitor] Diagrama de transición de estados UML

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#36]
Para ayudar a entender mejor los estados ( #29 ) del proceso de publicación de información del CENIEH en ARIADNE+, dejo como tarea dibujar un diagrama de transicción de estados UML.

**Comment by gcm1001** [comment]
![diagramatransicion](https://user-images.githubusercontent.com/44768603/79224744-f376e300-7e5b-11ea-8bae-82a4e448fdd6.png)

@clopezno ¿Esta implementación de estados sería correcta?

**Comment by clopezno** [comment]
Esa no es la idea  no se utilizan correctamente los diagramas de estado. El diagrama de estados en este caso se asocia a una clase, en tu caso ComponenteCENIEHPublicableenARIADNE.


He encontrado un ejemplo que puede servir como referencia. Se correspone con el modelado de un Objeto persistente en framework de persistencia de tipo Hibernate.

Dada la clase ObjetoPersistente y su diagrama de estados asociado, se muestra un nuevo diagrama de clases donde se aplica el patrón de diseño Estado. En el diagrama, a través de comentarios UML, se refleja cómo y quién realiza la transición de estados. Premisas sobre los objetos persistentes:

- Los objetos persistentes pueden insertarse, eliminarse o modificarse.
![image](https://user-images.githubusercontent.com/1453744/79240480-23c97c00-7e72-11ea-915b-adb70b6753f8.png)
- Operar sobre un objeto persistente (por ejemplo modificarlo) no provoca una actualización inmediata sobre la base de datos; se debe ejecutar una operación commit explícita.
![image](https://user-images.githubusercontent.com/1453744/79240546-39d73c80-7e72-11ea-80a0-2ad7e6499e39.png)

La aplicación del patrón de diseño estado

![image](https://user-images.githubusercontent.com/1453744/79240617-4eb3d000-7e72-11ea-952f-151d2892836e.png)

Espero que te ayude esta respuesta

Carlos López
