### ISSUE TITLE
Evaluar la calidad del código

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#45]
Herramientas a considerar:
- [Codacy](https://www.codacy.com/)
- [Codecov](https://codecov.io/)
- [CodeClimate](https://codeclimate.com/)

**Comment by gcm1001** [comment]
### Herramienta escogida
La opción escogida ha sido **Codacy** ya que, de entre las tres propuestas, es la que está más enfocada a la **revisión de código automatizada**, que es lo que nos interesa.
Como es lógico, soporta todos los lenguajes de programación que estoy utilizando ( _PHP_, _HTML_, _JavaScript_ y _CSS_ ). Además, la configuración de repositorios es muy sencilla gracias a su sencilla y elegante interfaz gráfica.

### Configuración
Como he dicho antes, la utilización de esta herramienta es muy simple. Simplemente hay que registrarse en su [página oficial](https://www.codacy.com) utilizando para ello la cuenta de Github, dar permisos a la aplicación, escoger una organización (si perteneces a alguna) y, por último, seleccionar el repositorio que quieras analizar. A partir de este momento, la herramienta analizará **todo el código** del repositorio cada vez que se ejecute un _commit_ sobre la rama principal. 


En mi caso, solo me interesa que analice la **parte de código que estoy desarrollando**, es decir, todos los ficheros alojados en la carpeta `PLUGINS` y `THEMES` pertenecientes a la carpeta `OMEKA`. Además, también es conveniente que analice todos los ficheros que he desarrollado para el despliegue automático (ficheros `.yaml` `.yml`). 

Para configurar las carpetas ignoradas, en la pestaña _Settings_ > _Ignored Files_, hay que seleccionar todas las carpetas que no he mencionado anteriormente.

![Screenshot_20200517_103547](https://user-images.githubusercontent.com/44768603/82139728-4d3b4600-982a-11ea-8726-23d02488820c.png)

Además se pueden realizar otras **configuraciones importantes** como:

- Activar / Desactivar **patrones de código** (A través de la interfaz o desde un fichero `.yml` alojado en tu repositorio).
- Seleccionar las **ramas** a analizar.
- Gestionar las **integraciones**.
- Configurar la calidad, es decir, establecer las **condiciones** en las que los _commits/pull request_ son exitosos o fallidos, e indicar el **umbral** a partir del cual tu repositorio es catalogado como "saludable".


[![Codacy Badge](https://app.codacy.com/project/badge/Grade/5a86b32c970a40a981b82a1324254596)](https://www.codacy.com/manual/gcm1001/TFG-CeniehAriadne?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=gcm1001/TFG-CeniehAriadne&amp;utm_campaign=Badge_Grade)

**Comment by clopezno** [comment]
Añade una tarea en GitLab llamada a **mantenimiento y calidad de código Codacy** donde analices en detalle los informes de codacy e intentes resolver algunas de las _issues_ para mejorar la calidad y pasar a una evaluación de B.
