### ISSUE TITLE
Publicar el CIR en ARIADNEplus

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#64]
Actualmente cuento con todos los ficheros necesarios para iniciar el proceso de importación de la colección CIR (*Issue* #58) en ARIADNEplus. Las tareas a realizar para concluir el proceso son:

1. Completar el cuestionario *on-line* desde donde ARIADNEplus recopila información sobre los socios.
2. Informar al líder del *Work Package 4* que tenemos completos tanto los metadatos (.xml) como el archivo de mapeo (.json) del vocabulario.
3. Esperar a ser notificado.
    - Esta notificación se efectúa cuando los metadatos han sido importados al portal fantasma.
4. Mostrar los resultados del portal fantasma al encargado del CENIEH y, si todo está bien, informar al lídel del WP4 que puede publicar los metadatos en el portal oficial de ARIADNEplus.

**Comment by gcm1001** [comment]
## Novedades
- Se ha rellenado el el cuestionario on-line.
- Se ha informado al líder del *Work Package 4* que tenemos completos tanto los metadatos (.xml) como el archivo de mapeo (.json) del vocabulario.
- Se me ha notificado que revisarán todos los ficheros y me informarán en cuanto hayan completado dicha revisión.  

El siguiente punto puede tomar dos variantes:
1. Los datos son correctos, por lo que se pasaría al punto 4 de los puntos indicados en la *Issue*.
2. Los datos necesitan ser completados/cambiados. En tal caso, se modificarían los ficheros involucrados y se volvería a ejecutar el punto 2 de los puntos indicados en la *Issue*.

En cuanto obtenga respuesta, actualizaré la *Issue*.

**Comment by gcm1001** [comment]
## Novedades 
El equipo de *ARIADNEplus* ha dado el visto bueno al fichero de transformación de mapeo, por lo que la importación a través del esquema de metadatos propuesto se podrá efectuar sin problema alguno.

En cuanto a los (meta)datos, nos han comentado que sólo están interesados en aquellos que puedan entrar dentro de la categoría "_FIELDWORK REPORT_". Mañana realizaré una reunión con Joseba y Javier para seleccionar qué (meta)datos son aptos y cuáles no.

Una vez tengamos listos los (meta)datos, volveré a contactar con el equipo de _ARIADNEplus_ para solicitar de nuevo la importación.

Además, he tenido que modificar el complemento "IsPartOfCollection" para añadir una nueva funcionalidad requerida por el proceso de importación del CIR. Esta permite automatizar la actualización del campo "_Source_" del esquema de metadatos "Dublin Core" para los ítems del CIR (serviría para cualquier ítem importado desde un repositorio _DSPACE_).

**Comment by clopezno** [comment]
Creo que esta es la mejor prueba de aceptación de los resultados de tu proyecto.
¡Buen trabajo!

**Comment by gcm1001** [comment]
## Novedades
ARIADNEplus ya ha confirmado que los datos son aptos para ser importados en el portal fantasma, por lo que la tarea puede darse por finalizada. Quedamos a la espera de obtener el enlace al portal fantasma.
