### ISSUE TITLE
Finalización de la memoria.

### ISSUE THREAD

**Issue by gcm1001** [gcm1001/TFG-CeniehAriadne#72]
El objetivo de esta tarea es finalizar con la documentación de la memoria. Para ello se realizarán las siguientes tareas:

- [x] Revisar cada uno de los apartados, realizando las modificaciones que se consideren oportunas.
- [x] Convertir los ficheros de la memoria (.rst ) a LaTeX (.tex) haciendo uso de la herramienta [pandoc](https://pandoc.org/).

**Comment by clopezno** [comment]
¡Gran trabajo Gonzalo!
Leyendo tu trabajo he disfrutado y aprendido ;-)

Adjunto el documento pdf de revisión de la memoria con algunos comentarios menores en el pdf.
[memoria_notas_mario_carlos.pdf](https://github.com/gcm1001/TFG-CeniehAriadne/files/4930764/memoria_notas_mario_carlos.pdf)
